document.write('<div class=\"main-footer-area\">\n');
document.write('            <div class=\"container\">\n');
document.write('                <div class=\"row justify-content-between\">\n');
document.write('                    <!-- Single Footer Widget Area -->\n');
document.write('                    <div class=\"col-6 col-sm-4 col-lg-2\">\n');
document.write('                        <div class=\"single-footer-widget mb-80\">\n');
document.write('                            <!-- Widget Title -->\n');
document.write('                            <h5 class=\"widget-title\">Products</h5>\n');
document.write('                            <!-- Footer Nav -->\n');
document.write('                            <ul class=\"footer-nav\">\n');
document.write('                                <li><a href=\"#\">Home</a></li>\n');
document.write('                                <li><a href=\"#\">Daftar Harga</a></li>\n');
document.write('                                <li><a href=\"#\">Registrasi</a></li>\n');
document.write('                                <li><a href=\"#\">Panduan</a></li>\n');
document.write('                                <li><a href=\"./webreporting.html\" target=\"_blank\">Webreport</a></li>\n');
document.write('                                <li><a href=\"./kontak.html\">Kontak</a></li>\n');
document.write('                            </ul>\n');
document.write('                        </div>\n');
document.write('                    </div>\n');
document.write('                    <!-- Single Footer Widget Area -->\n');
document.write('                    <div class=\"col-6 col-sm-4 col-lg-2\">\n');
document.write('                        <div class=\"single-footer-widget mb-80\">\n');
document.write('                            <!-- Widget Title -->\n');
document.write('                            <center>\n');
document.write('                                <h5 class=\"widget-title\">Tiket Deposit</h5>\n');
document.write('                            </center>\n');
document.write('                            <!-- Footer Nav -->\n');
document.write('                            <ul class=\"footer-nav\">\n');
document.write('                                <center><a href=\"https://otopulsa.com/download.html\" target=\"_blank\">\n');
document.write('                                        <img class=\"d-block ml-1 mx-auto\" src=\"img/scr-img/bca.webp\" width=\"100 px\"\n');
document.write('                                            height=\"auto\" alt=\"google play oto pulsa\"></a>\n');
document.write('                                    <li><a>3030596195</a></li>\n');
document.write('                                    <p></p>\n');
document.write('                                    <a href=\"https://otopulsa.com/download.html\" target=\"_blank\">\n');
document.write('                                        <img class=\"d-block ml-1 mx-auto\" src=\"img/scr-img/mandiri.webp\" width=\"100 px\"\n');
document.write('                                            height=\"auto\" alt=\"google play oto pulsa\"></a>\n');
document.write('                                    <li><a>1340013484935</a></li>\n');
document.write('                                    <p></p>\n');
document.write('                                    <a href=\"https://otopulsa.com/download.html\" target=\"_blank\">\n');
document.write('                                        <img class=\"d-block ml-1 mx-auto\" src=\"img/scr-img/bni.webp\" width=\"100 px\"\n');
document.write('                                            height=\"auto\" alt=\"google play oto pulsa\"></a>\n');
document.write('                                    <li><a>0673719166</a></li>\n');
document.write('                                    <p></p>\n');
document.write('                                    <a href=\"https://otopulsa.com/download.html\" target=\"_blank\">\n');
document.write('                                        <img class=\"d-block ml-1 mx-auto\" src=\"img/scr-img/bri.webp\" width=\"100 px\"\n');
document.write('                                            height=\"auto\" alt=\"google play oto pulsa\"></a>\n');
document.write('                                    <li><a>002801103250508</a></li>\n');
document.write('                                    <li><a>A/N : Daniel Corsel</a></li>\n');
document.write('                                </center>\n');
document.write('                            </ul>\n');
document.write('                        </div>\n');
document.write('                    </div>\n');
document.write('                    <!-- Single Footer Widget Area -->\n');
document.write('                    <div class=\"col-12 col-sm-8 col-lg-4\">\n');
document.write('                        <div class=\"single-footer-widget mb-80\">\n');
document.write('                            <!-- Widget Title -->\n');
document.write('                            <h5 class=\"widget-title\">Subscribe Newsletter</h5>\n');
document.write('                            <p>Subscribe to our email newsletter for useful tips and valuable resources.</p>\n');
document.write('                            <!-- Newsletter Form -->\n');
document.write('                            <!-- Social Info -->\n');
document.write('                            <div class=\"social-info\">\n');
document.write('                                <a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\n');
document.write('                                <a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\n');
document.write('                                <a href=\"#\" class=\"google-plus\"><i class=\"fa fa-telegram\" aria-hidden=\"true\"></i></a>\n');
document.write('                                <a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\n');
document.write('                                <a href=\"#\" class=\"youtube\"><i class=\"fa fa-youtube\" aria-hidden=\"true\"></i></a>\n');
document.write('                            </div>\n');
document.write('                        </div>\n');
document.write('                    </div>\n');
document.write('                </div>\n');
document.write('            </div>\n');
document.write('        </div>');