document.write('<nav class=\"classy-navbar justify-content-between\" id=\"hamiNav\">\n');
document.write('                        <!-- Logo -->\n');
document.write('                        <a class=\"nav-brand\" href=\"./index.html\"><img src=\"./img/core-img/logo.webp\" alt=\"\"></a>\n');
document.write('                        <!-- Navbar Toggler -->\n');
document.write('                        <div class=\"classy-navbar-toggler\">\n');
document.write('                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\n');
document.write('                        </div>\n');
document.write('                        <!-- Menu -->\n');
document.write('                        <div class=\"classy-menu\">\n');
document.write('                            <!-- Menu Close Button -->\n');
document.write('                            <div class=\"classycloseIcon\">\n');
document.write('                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\n');
document.write('                            </div>\n');
document.write('                            <!-- Nav Start -->\n');
document.write('                            <div class=\"classynav\">\n');
document.write('                                <ul id=\"nav\">\n');
document.write('                                    <li><a href=\"./index.html\">Home</a></li>\n');
document.write('                                    <li><a href=\"./harga.html\">Daftar Harga</a></li>\n');
document.write('                                    <li><a href=\"./registrasi.html\">Registrasi</a></li>\n');
document.write('                                    <li><a href=\"#\">Panduan</a>\n');
document.write('                                        <ul class=\"dropdown\">\n');
document.write('                                            <li><a href=\"./format-transaksi.html\">- Format Transaksi</a></li>\n');
document.write('                                            <li><a href=\"./seting-android.html\">- Seting Android</a></li>\n');
document.write('                                            <li><a href=\"./seting-h2h.html\">- Seting Parsing H2H</a></li>\n');
document.write('                                            <li><a href=\"./seting-telegram.html\">- Seting Telegram</a></li>\n');
document.write('                                            <li><a href=\"./seting-jabber.html\">- Seting Jabber</a></li>\n');
document.write('                                            <li><a href=\"./seting-gtalk.html\">- Seting Gtalk</a></li>\n');
document.write('                                            <li><a href=\"#\">- Dropdown</a>\n');
document.write('                                                <ul class=\"dropdown\">\n');
document.write('                                                    <li><a href=\"#\">- Dropdown Item</a></li>\n');
document.write('                                                    <li><a href=\"#\">- Dropdown Item</a></li>\n');
document.write('                                                    <li><a href=\"#\">- Dropdown Item</a></li>\n');
document.write('                                                    <li><a href=\"#\">- Dropdown Item</a></li>\n');
document.write('                                                </ul>\n');
document.write('                                            </li>\n');
document.write('                                        </ul>\n');
document.write('                                    </li>\n');
document.write('                                    <li><a href=\"./download.html\" target=\"_blank\">Download</a></li>\n');
document.write('                                    <li><a href=\"./kontak.html\">Kontak</a></li>\n');
document.write('                                </ul>\n');
document.write('                                <!-- Live Chat -->\n');
document.write('                                <div class=\"live-chat-btn ml-5 mt-4 mt-lg-0 ml-md-4\">\n');
document.write('                                    <a href=\"#\" class=\"btn hami-btn live--chat--btn\"><i class=\"fa fa-comments\"\n');
document.write('                                            aria-hidden=\"true\"></i> Live Chat</a>\n');
document.write('                                </div>\n');
document.write('                            </div>\n');
document.write('                            <!-- Nav End -->\n');
document.write('                        </div>\n');
document.write('                    </nav>');