document.write( '<div class=\"col-md-4 border-left text-center \" style=\"\">\n' );
document.write( '                <div align=\"center\"\n' );
document.write( '                  style=\"background-color: white; box-sizing: border-box; color: #686868;font-size: 13px;line-height: 19px;\">\n' );
document.write( '                  <div class=\"error\"\n' );
document.write( '                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n' );
document.write( '                    <div class=\"message_box_content\"\n' );
document.write( '                      style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 12px;\">\n' );
document.write( '                      <h4>Aplikasi Android</h4> <a title=\"download aplikasi OTO Pulsa\" href=\"../download.html\"\n' );
document.write( '                        target=\"_blank\" rel=\"noopener noreferrer\"><img alt=\"aplikasi otopulsa pulsa murah\"\n' );
document.write( '                          src=\"../img/scr-img/googleplay.webp\" width=\"150\"></a>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '\n' );
document.write( '                  <div class=\"error\"\n' );
document.write( '                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n' );
document.write( '                    <div class=\"message_box_content\"\n' );
document.write( '                      style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 12px;\">\n' );
document.write( '                      <h4>CS</h4><a class=\"btn btn-primary btn-lg m-2\"\n' );
document.write( '                        href=\"https://api.whatsapp.com/send?phone=6285642100966&text=https%3A%2F%2Fotopulsa.com%0AIsi%20Pesan%20%2F%20Pertanyaan%20Anda%20%3A%20%0A\"\n' );
document.write( '                        target=\"_blank\">Chat Via WA</a>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '\n' );
document.write( '                  <div class=\"error\"\n' );
document.write( '                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n' );
document.write( '                    <div class=\"message_box_content\"\n' );
document.write( '                      style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 12px;\">\n' );
document.write( '                      <h4>Center Transaksi</h4>\n' );
document.write( '                      <strong>SMS</strong><br>\n' );
document.write( '                      <strong>0895-4150-91175<br>0838-9062-5586<br>0859-1215-30712<br></strong><br>\n' );
document.write( '                      <strong>JABBER</strong><br>\n' );
document.write( '                      <strong>otopulsa1@chat.tigaputri.asia<br>otopulsa@jabber.ru<br>otopulsa@im.ajs.id<br></strong><br>\n' );
document.write( '                      <strong>WhatsApp</strong><br>\n' );
document.write( '                      <strong><a href=\"https://api.whatsapp.com/send?phone=62895415091175&text=SAL.\"\n' );
document.write( '                          target=\"_blank\">+62895415091175</a></strong>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '\n' );
document.write( '                  <div class=\"error\"\n' );
document.write( '                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n' );
document.write( '                    <div class=\"message_box_content\"\n' );
document.write( '                      style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 12px;\">\n' );
document.write( '                      <h4>Deposit TopUp</h4>\n' );
document.write( '                      <strong><span style=\"color:red;font-size:115%;\">3030596195</span></strong><br><img\n' );
document.write( '                        alt=\"deposit saldo pulsa bca\" src=\"../img/scr-img/bca.webp\" width=\"150\"\n' );
document.write( '                        height=\"61\"><br><strong><span\n' );
document.write( '                          style=\"color:red;font-size:115%;\">1340013484935</span></strong><br><img\n' );
document.write( '                        alt=\"deposit saldo pulsa mandiri\" src=\"../img/scr-img/mandiri.webp\" width=\"150\"\n' );
document.write( '                        height=\"61\"><br><strong><span\n' );
document.write( '                          style=\"color:red;font-size:115%;\">0000000000</span></strong><br><img\n' );
document.write( '                        alt=\"deposit saldo pulsa bni\" src=\"../img/scr-img/bni.webp\" width=\"150\"\n' );
document.write( '                        height=\"61\"><br><strong><span\n' );
document.write( '                          style=\"color:red;font-size:115%;\">002801103250508</span></strong><br><img\n' );
document.write( '                        alt=\"deposit saldo pulsa bri\" src=\"../img/scr-img/bri.webp\" width=\"150\" height=\"61\"><br>Semua\n' );
document.write( '                      Rekening A/N : <br><span style=\"color:blue;font-size:115%;\"><strong>Daniel\n' );
document.write( '                          Corsel </strong></span>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '\n' );
document.write( '                  <div class=\"error\"\n' );
document.write( '                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n' );
document.write( '                    <div class=\"message_box_content\"\n' );
document.write( '                      style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 12px;\">\n' );
document.write( '                      Deposit gunakan Sistem Tiket, agar deposit Anda masuk secara\n' );
document.write( '                      otomatis<br>Panduannya disini » <strong><a href=\"https://otopulsa.com/deposit.html\"\n' );
document.write( '                          title=\"cara deposit saldo pulsa\">Cara isi saldo pulsa</a></strong>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '                </div>\n' );
document.write( '              </div>' );
