document.write('<div class=\"col-md-4 border-left text-center \" style=\"\">\n');
document.write('                                <h4 class=\"bg-primary text-white rounded-circle\">APLIKASI ANDROID</h4>\n');
document.write('                                <div class=\" textwidget custom-html-widget\"><a title=\"download aplikasi otopulsa pulsa\"\n');
document.write('                                        href=\"../download.html\" target=\"_blank\"\n');
document.write('                                        rel=\"noopener noreferrer\"><img alt=\"aplikasi otopulsa pulsa murah\"\n');
document.write('                                            src=\"../img/scr-img/googleplay.webp\" width=\"150\"></a><br><br>\n');
document.write('                                    <div class=\"widget_text box\">\n');
document.write('                                        <h4 class=\"bg-primary text-white rounded-circle\">CUSTOMER SERVICE</h4>\n');
document.write('                                        <div class=\"textwidget custom-html-widget\">\n');
document.write('                                            <div align=\"center\">Phone : <strong>085642100966</strong><br><br><strong>CS\n');
document.write('                                                    Transaksi & Deposit</strong><br><a\n');
document.write('                                                    href=\"tg://resolve?domain=otopulsa_admx\"><img\n');
document.write('                                                        alt=\"cs otopulsa pulsa murah\" src=\"../img/scr-img/telegram.webp\"\n');
document.write('                                                        width=\"125\" height=\"37\"></a>\n');
document.write('                                                <br>\n');
document.write('                                                <div class=\"widget_text box\">\n');
document.write('                                                    <h4 class=\"bg-primary text-white rounded-circle\">CENTER TRANSAKSI\n');
document.write('                                                    </h4>\n');
document.write('                                                    <div class=\"textwidget custom-html-widget\">\n');
document.write('                                                        <div align=\"center\"><span\n');
document.write('                                                                style=\"font-size:115%;\"><strong>0838-9062-5586<br>0859-1215-30712<br>0895-1387-6974<br>0896-5217-3202<br></strong></span><br></strong></span><br><strong><span\n');
document.write('                                                                    style=\"color:blue;\">TELEGRAM</span></strong><br><a\n');
document.write('                                                                href=\"tg://resolve?domain=ctr_otopulsabot\"><img\n');
document.write('                                                                    alt=\"cs otopulsa pulsa murah\"\n');
document.write('                                                                    src=\"../img/scr-img/telegram.webp\" width=\"125\"\n');
document.write('                                                                    height=\"37\"></a><a\n');
document.write('                                                                href=\"tg://resolve?domain=ctr_otopulsabot\"><img\n');
document.write('                                                                    alt=\"cs otopulsa pulsa murah\"\n');
document.write('                                                                    src=\"../img/scr-img/telegram.webp\" width=\"125\"\n');
document.write('                                                                    height=\"37\"></a><br><br><strong><span\n');
document.write('                                                                    style=\"color:blue;\">WhatsApp\n');
document.write('                                                                    Center</span></strong><br><strong>089513876974</strong><br><img\n');
document.write('                                                                alt=\"trx whatsapp pulsa murah\"\n');
document.write('                                                                src=\"../img/scr-img/wa.webp\" width=\"125\"\n');
document.write('                                                                height=\"37\"><br><span style=\"color:green;\"></span>\n');
document.write('                                                        </div>\n');
document.write('                                                    </div><br>\n');
document.write('                                                    <div class=\"widget_text box\">\n');
document.write('                                                        <h4 class=\"bg-primary text-white rounded-circle\">BANK DEPOSIT\n');
document.write('                                                        </h4>\n');
document.write('                                                        <div class=\"textwidget custom-html-widget\">\n');
document.write('                                                            <div align=\"center\"><strong><span\n');
document.write('                                                                        style=\"color:red;font-size:115%;\">3030596195</span></strong><br><img\n');
document.write('                                                                    alt=\"deposit saldo pulsa bca\"\n');
document.write('                                                                    src=\"../img/scr-img/bca.webp\" width=\"150\"\n');
document.write('                                                                    height=\"61\"><br><strong><span\n');
document.write('                                                                        style=\"color:red;font-size:115%;\">1340013484935</span></strong><br><img\n');
document.write('                                                                    alt=\"deposit saldo pulsa mandiri\"\n');
document.write('                                                                    src=\"../img/scr-img/mandiri.webp\" width=\"150\"\n');
document.write('                                                                    height=\"61\"><br><strong><span\n');
document.write('                                                                        style=\"color:red;font-size:115%;\">0000000000</span></strong><br><img\n');
document.write('                                                                    alt=\"deposit saldo pulsa bni\"\n');
document.write('                                                                    src=\"../img/scr-img/bni.webp\" width=\"150\"\n');
document.write('                                                                    height=\"61\"><br><strong><span\n');
document.write('                                                                        style=\"color:red;font-size:115%;\">002801103250508</span></strong><br><img\n');
document.write('                                                                    alt=\"deposit saldo pulsa bri\"\n');
document.write('                                                                    src=\"../img/scr-img/bri.webp\" width=\"150\"\n');
document.write('                                                                    height=\"61\"><br>Semua Rekening A/N : <br><span\n');
document.write('                                                                    style=\"color:blue;font-size:115%;\"><strong>Daniel\n');
document.write('                                                                        Corsel </strong></span><br>\n');
document.write('                                                                <br>\n');
document.write('                                                            </div>\n');
document.write('                                                            <div align=\"center\"\n');
document.write('                                                                style=\"background-color: white; box-sizing: border-box; color: #686868;font-size: 13px;line-height: 19px;\">\n');
document.write('                                                                <div class=\"error\"\n');
document.write('                                                                    style=\"background: rgb(253, 233, 234); border-radius: 5px; border: 1px solid rgb(253, 206, 208); box-sizing: border-box; color: #a14a40; margin-bottom: 20px;\">\n');
document.write('                                                                    <div class=\"message_box_content\"\n');
document.write('                                                                        style=\"border-radius: 5px; border: 1px solid rgb(255, 255, 255); box-sizing: border-box;padding: 10px;\">\n');
document.write('                                                                        Deposit gunakan Sistem Tiket, agar deposit Anda\n');
document.write('                                                                        masuk secara otomatis<br>Panduannya disini »\n');
document.write('                                                                        <strong><a\n');
document.write('                                                                                href=\"https://otopulsa.com/deposit.html\"\n');
document.write('                                                                                title=\"cara deposit saldo pulsa\">Cara\n');
document.write('                                                                                isi saldo pulsa</a></strong>\n');
document.write('                                                                    </div>\n');
document.write('                                                                </div>\n');
document.write('                                                            </div>\n');
document.write('                                                        </div>\n');
document.write('                                                    </div>\n');
document.write('                                                </div>\n');
document.write('                                            </div>\n');
document.write('                                        </div>\n');
document.write('                                    </div>\n');
document.write('                                </div>\n');
document.write('                            </div>');