document.write('<div class=\"container\">\n');
document.write('                <div class=\"row\">\n');
document.write('                    <div class=\"col-6\">\n');
document.write('                        <div class=\"top-header-content\">\n');
document.write('                            <a href=\"#\"><i class=\"fa fa-whatsapp\" aria-hidden=\"true\"></i> <span>Chat:\n');
document.write('                                    0856-4210-0966</span></a>\n');
document.write('                            <a href=\"#\"><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> <span>Email:\n');
document.write('                                    </span></a>\n');
document.write('                        </div>\n');
document.write('                    </div>\n');
document.write('                    <div class=\"col-6\">\n');
document.write('                        <div class=\"top-header-content\">\n');
document.write('                            <!-- Login -->\n');
document.write('                            <a href=\"../webreporting.html\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i> <span>Webreport</span></a>\n');
document.write('                            <!-- Language -->\n');
document.write('                            <div class=\"dropdown\">\n');
document.write('                                <a class=\"btn pr-0 dropdown-toggle\" href=\"#\" role=\"button\" id=\"langdropdown\"\n');
document.write('                                    data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><img\n');
document.write('                                        src=\"img/core-img/eng.webp\" alt=\"\"> Indonesia</a>\n');
document.write('                                <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"langdropdown\">\n');
document.write('                                    <a class=\"dropdown-item\" href=\"#\">- English</a>\n');
document.write('                                </div>\n');
document.write('                            </div>\n');
document.write('                        </div>\n');
document.write('                    </div>\n');
document.write('                </div>\n');
document.write('            </div>');